import { StyleSheet } from "react-native";
import { colors } from "../../styles/colors";

export const styles = StyleSheet.create({
  shop: {
    width: "100%",
    flex: 1,
  },
  header: {
    width: "100%",
    backgroundColor: colors.dark,
    height: 240,
    paddingRight: 20,
    paddingLeft: 20,
  },
  container: {
    paddingTop: 25,
    flexDirection: "row",
    justifyContent: "center",
    maxHeight: 80,
  },
  containerInput: {
    marginRight: 15,
    height: "100%",
  },
  input: {
    width: 300,
    backgroundColor: colors.coal,
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 60,
    paddingRight: 15,
    borderRadius: 12,
    fontSize: 18,
    color: colors.white,
    height: "100%",
  },
  iconSearch: {
    position: "absolute",
    top: "25%",
    left: 15,
  },
  menu: {
    width: 55,
    height: "100%",
    borderRadius: 12,
    backgroundColor: colors.brick,
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    marginTop: -90,
    paddingRight: 20,
    paddingLeft: 20,
    flex: 1,
  },
  banner: {
    width: "100%",
    height: 150,
  },
  bodyBanner: {
    width: "100%",
    borderRadius: 16,
    height: 150,
    overflow: "hidden",
    marginBottom: 25,
  },
  titleBanner: {
    color: colors.white,
    marginLeft: 30,
    fontSize: 32,
    fontWeight: "700",
  },
  info: {
    width: 80,
    height: 40,
    backgroundColor: colors.lightRed,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    marginLeft: 30,
    marginBottom: 15,
  },
  textInfo: {
    color: colors.white,
    fontWeight: "700",
    fontSize: 18,
  },
  bodyCoffee: {
    flex: 1,
  },
  star: {
    marginRight: 10,
  },
  item: {
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 15,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  textCoffee: {
    fontSize: 18,
    fontWeight: "500",
    textAlign: "center",
  },
  list: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    paddingBottom: 20,
  },
  itemCoffee: {
    width: 170,
    height: 280,
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    backgroundColor: colors.white,
    shadowColor: "#000",
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 12,
  },
  imageCoffee: {
    maxHeight: 150,
    height: "100%",
    overflow: "hidden",
    borderRadius: 12,
    marginBottom: 10,
  },
  bodyRating: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginRight: 20,
    marginTop: 10,
  },
  ratingText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
  },
  titleCoffe: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 5,
  },
  textCoffe: {
    opacity: 0.5,
    fontSize: 16,
    marginBottom: 10,
  },
  wrapperCoffee: {
    flexDirection: "row",
    alignItems: "center",
  },
  priceCoffee: {
    fontSize: 20,
    fontWeight: "700",
    flex: 1,
  },
  actionCoffee: {
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    backgroundColor: colors.brick,
    borderRadius: 8,
  },
});
